// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALzSBjJgbkUgjhAtfPZY7otB5ylKAWHTE',
    appId: '1:945943317018:web:15ed1f9a126264442fdfa3',
    messagingSenderId: '945943317018',
    projectId: 'budgetpersonnal',
    authDomain: 'budgetpersonnal.firebaseapp.com',
    storageBucket: 'budgetpersonnal.appspot.com',
    measurementId: 'G-DK2G05V3ZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJoPHcpQ4e6N2SSHqBAZul8miJcS-aoY8',
    appId: '1:945943317018:android:8b35c79fb92278ac2fdfa3',
    messagingSenderId: '945943317018',
    projectId: 'budgetpersonnal',
    storageBucket: 'budgetpersonnal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBESKqbGXs_cLkrhcZv0KjWJKTF1mIFU_0',
    appId: '1:945943317018:ios:087f5750d10ac9762fdfa3',
    messagingSenderId: '945943317018',
    projectId: 'budgetpersonnal',
    storageBucket: 'budgetpersonnal.appspot.com',
    androidClientId: '945943317018-jfs2e235ejn8iu3s9b32loo9fftaps3s.apps.googleusercontent.com',
    iosClientId: '945943317018-pm79se4ftfc1ccna5qan95c1jj5crbr3.apps.googleusercontent.com',
    iosBundleId: 'com.budget.budgetManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBESKqbGXs_cLkrhcZv0KjWJKTF1mIFU_0',
    appId: '1:945943317018:ios:087f5750d10ac9762fdfa3',
    messagingSenderId: '945943317018',
    projectId: 'budgetpersonnal',
    storageBucket: 'budgetpersonnal.appspot.com',
    androidClientId: '945943317018-jfs2e235ejn8iu3s9b32loo9fftaps3s.apps.googleusercontent.com',
    iosClientId: '945943317018-pm79se4ftfc1ccna5qan95c1jj5crbr3.apps.googleusercontent.com',
    iosBundleId: 'com.budget.budgetManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALzSBjJgbkUgjhAtfPZY7otB5ylKAWHTE',
    appId: '1:945943317018:web:67e1ca58c4320ce72fdfa3',
    messagingSenderId: '945943317018',
    projectId: 'budgetpersonnal',
    authDomain: 'budgetpersonnal.firebaseapp.com',
    storageBucket: 'budgetpersonnal.appspot.com',
    measurementId: 'G-LDSPB0T438',
  );
}
