name: budget_management
description: "A budget management app with flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6

  shared_preferences: ^2.3.2

  firebase_core: ^3.4.1
  firebase_auth: ^5.2.1
  firebase_storage: ^12.3.0
  cloud_firestore: ^5.4.1

  # Map
  geolocator: ^12.0.0
  latlong2: ^0.9.1
  flutter_map: ^7.0.2
  flutter_map_cancellable_tile_provider: ^3.0.0
  geocoding: ^2.0.4
  nominatim_geocoding: ^0.0.6
  get: ^4.6.5


  # Image
  image_picker: ^1.1.2

  # Utils
  intl: ^0.19.0
  uuid: ^4.4.0
  permission_handler: ^10.2.0
  flutter_local_notifications: ^17.1.2

  # Other
  flutter_speed_dial: ^7.0.0
  another_flushbar: ^1.10.24
  fl_chart: ^0.69.0
  flutter_slidable: ^3.1.1
  random_color: ^1.0.6-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/icons/bell_notification.webp

