// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMh3aw7EgwBf4Lbu0swFtDSCTBBTRpuhE',
    appId: '1:95422398859:web:52f36a056ec08b5b89ef8e',
    messagingSenderId: '95422398859',
    projectId: 'myfinances-45a97',
    authDomain: 'myfinances-45a97.firebaseapp.com',
    storageBucket: 'myfinances-45a97.firebasestorage.app',
    measurementId: 'G-Y9941GQXWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSrXzuv7bKppP7BGJuU0aiDPPC5-GZT7E',
    appId: '1:95422398859:android:2def72752ac0e87189ef8e',
    messagingSenderId: '95422398859',
    projectId: 'myfinances-45a97',
    storageBucket: 'myfinances-45a97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB52YtOIsQ27xTDEB60YddgFdUFR8nnzRQ',
    appId: '1:95422398859:ios:cb6596be504c7f9589ef8e',
    messagingSenderId: '95422398859',
    projectId: 'myfinances-45a97',
    storageBucket: 'myfinances-45a97.firebasestorage.app',
    iosBundleId: 'com.example.myfinances',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB52YtOIsQ27xTDEB60YddgFdUFR8nnzRQ',
    appId: '1:95422398859:ios:cb6596be504c7f9589ef8e',
    messagingSenderId: '95422398859',
    projectId: 'myfinances-45a97',
    storageBucket: 'myfinances-45a97.firebasestorage.app',
    iosBundleId: 'com.example.myfinances',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMh3aw7EgwBf4Lbu0swFtDSCTBBTRpuhE',
    appId: '1:95422398859:web:b42cc69046fc22a289ef8e',
    messagingSenderId: '95422398859',
    projectId: 'myfinances-45a97',
    authDomain: 'myfinances-45a97.firebaseapp.com',
    storageBucket: 'myfinances-45a97.firebasestorage.app',
    measurementId: 'G-11882KFYKF',
  );
}
