name: budget_management
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.6
  image_picker: ^1.1.2
  geolocator: ^13.0.2
  firebase_auth: ^5.3.3
  another_flushbar: ^1.12.30
  intl: ^0.19.0
  flutter_map: ^7.0.2
  flutter_slidable: ^3.1.1
  geocoding: ^3.0.0
  get: ^4.6.6
  nominatim_geocoding: ^0.0.6
  shared_preferences: ^2.3.3
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true